name: 0
on:
  push:
    tags:        
      - * 
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 0 to bin0.txt
        run: echo 0 > bin0.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin0
          path: bin0.txt
      - name: Upload artifact to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bin0.txt
