name: 1
on:
  push:
    tags:        
      - '*' 
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 1 to bin1.txt
        run: echo 1 > bin1.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin1
          path: bin1.txt
      - name: Upload artifact to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: bin1.txt
