name: 2
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Echo 2 to bin2.txt
        run: echo 2 > bin2.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bin2
          path: bin2.txt
      - name: Upload artifact to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: bin2
          files: bin2.txt
          tag_name: {{ github.ref }}
